[package]
name = "autoscript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = {version="7", default-features = true}
num-cmp = "0.1.0"
clap = { version = "4.0.2", features = ["derive"] }
